### PR TITLE
fix: Fix issues with failed interaction | feature: Add compatibility for discord.js dev (v14)

### PR DESCRIPTION
**Pull request by 3061LRTAGSPKJMORMRT**
- Used `deferUpdate` and `editReply()` when an interaction is recieved.
- Possible fix for WillTDA/Discord.js-Akinator-Package-Dev/issues/18

### CODE REVIEW

**Comment by WillTDA** [comment]
Does this work on both v13 and v14?

**Comment by 3061LRTAGSPKJMORMRT** [comment]
No, that's the other PR, however I will maintain that one

**Comment by 3061LRTAGSPKJMORMRT** [comment]
Alright, I have tested the and the current code DOES work for dev (v14) and v13.

This PR can be merged.

**Comment by WillTDA** [comment]
Merged 👍

Also, just wanted to say, I didn't realise how much time you've spent helping to develop this! Thanks mate, you are a lifesaver.

**Comment by 3061LRTAGSPKJMORMRT** [comment]
No worries!

**Pull request merged**
